services:

  mariadb:
    image: mariadb:10.11
    container_name: mariadb-database
    restart: always
    ports:
      - "53306:3306"
    env_file:
      - ./config/.env
    volumes:
      - ./data:/var/lib/mysql
      - ./config/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
      - ./config/custom.cnf:/etc/mysql/conf.d/custom.cnf:ro
    networks:
      - mariadb-network

networks:
  mariadb-network:
    external: true