#!/bin/bash
set -e

# 도커 환경변수에서 가져온 루트 비번으로 마리아디비 명령 실행
mariadb -u root -p"${MARIADB_ROOT_PASSWORD}" <<EOF

-- 1. SSUACE프로젝트 전용 DB 및 유저 생성
CREATE DATABASE IF NOT EXISTS ${SSUACE_DB};
CREATE USER IF NOT EXISTS '${SSUACE_USER}'@'%' IDENTIFIED BY '${SSUACE_PASSWORD}';
GRANT ALL PRIVILEGES ON ${SSUACE_DB}.* TO '${SSUACE_USER}'@'%';

FLUSH PRIVILEGES;
EOF