#!/bin/bash
set -e

# 마리아디비 명령 실행
mariadb -u root -p"${MARIADB_ROOT_PASSWORD}" <<EOF

-- 1. 모든 프로젝트용 마스터유저 생성
CREATE USER IF NOT EXISTS '${MASTER_USER}'@'%' IDENTIFIED BY '${MASTER_PASSWORD}';
GRANT ALL PRIVILEGES ON *.* TO '${MASTER_USER}'@'%' WITH GRANT OPTION;

-- 2. SSUACE프로젝트 전용 DB 및 유저 생성
CREATE DATABASE IF NOT EXISTS ${SSUACE_DB};
CREATE USER IF NOT EXISTS '${SSUACE_USER}'@'%' IDENTIFIED BY '${SSUACE_PASSWORD}';
GRANT ALL PRIVILEGES ON ${SSUACE_DB}.* TO '${SSUACE_USER}'@'%';

FLUSH PRIVILEGES;
EOF