name: mariadb

on:
  push:
    branches:
      - main  # 💡 실제 배포 브랜치명으로 맞추세요

jobs:
  # 서버 원격 접속 및 실시간 배포
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH Environment
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p ${{ secrets.SERVER_PORT }} -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via SSH Command
        run: |
          ssh -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            echo "🍏 서버 접속 완벽 성공! 전체 서비스 배포를 시작합니다."

            # 최상단 도커 컴포즈 파일이 있는 서버 경로로 이동
            cd ${{ secrets.SERVER_PATH }}

            # 1) 새 코드 다운로드
            git pull

            # 2) 컨테이너 전체 재시작
            docker compose up -d

            # 3) 구버전 이미지 찌꺼기 청소
            docker image prune -f

            echo "🍎 모든 서비스 배포 완료"
          EOF